- type: gameMapPool
  id: TPMapPool
  maps:
  - Star

- type: shipSpawnPool
  id: Default
  ships:
    Spade:
      crewRole: TPWanderer
      maxPlayers: 2
    Star:
      crewRole: TPWanderer
      maxPlayers: 3
    Piracy:
      crewRole: TPWanderer
      maxPlayers: 3
    BoxShuttle:
      crewRole: TPWanderer
      maxPlayers: 3
