- type: worldgenConfig
  id: TPDefault
  components:
  - type: WorldController
  - type: BiomeSelection
    biomes:
    - TPTheVoid # The void consumes.
    - TPAsteroidsStandard
  - type: WorldShipSpawner
