- type: worldgenConfig
  id: TPDefault
  components:
  - type: WorldController
  - type: BiomeSelection
    biomes:
    - TPTheVoid # The void consumes.
    - TPStandard
    - TPSand
    - TPSnow
    - TPFlesh
  - type: WorldShipSpawner
