- type: dungeonConfig
  id: TPBasic
  generator: !type:PrefabDunGen
    roomWhitelist:
    - TPDungeonBasic
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall
  postGeneration:
  - !type:CorridorPostGen
    width: 3

  - !type:RoomEntrancePostGen
    entities:
    - WoodDoor

  - !type:WallMountPostGen
    spawns:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

  - !type:BoundaryWallPostGen
    tile: FloorSteel
    wall: WallSolid
    cornerWall: WallReinforced

  - !type:CornerClutterPostGen
    contents:
    - id: PottedPlantRandom
      amount: 1

- type: dungeonConfig
  id: TPSand
  generator: !type:PrefabDunGen
    roomWhitelist:
    - TPDungeonSand
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall
    tile: FloorAsteroidTile
  postGeneration:
  - !type:CorridorPostGen
    width: 3
    tile: FloorAsteroidTile

  - !type:RoomEntrancePostGen
    entities:
    - WoodDoor
    tile: FloorAsteroidTile

  - !type:WallMountPostGen
    spawns:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

  - !type:BoundaryWallPostGen
    tile: FloorAsteroidTile
    wall: WallSandstone
    cornerWall: WallSandstone

  - !type:CornerClutterPostGen
    contents:
    - id: PottedPlantRandom
      amount: 1

