- type: dungeonConfig
  id: TPBasic
  generator: !type:PrefabDunGen
    roomWhitelist:
    - TPDungeonBasic
    presets:
    - Bucket
    - Wow
    - SpaceShip
    - Tall
  postGeneration:
  - !type:CorridorPostGen
    width: 3

  - !type:DungeonEntrancePostGen
    count: 2

  - !type:EntranceFlankPostGen
    entities:
    - Grille
    - Window

  - !type:ExternalWindowPostGen
    entities:
    - Grille
    - Window

  - !type:WallMountPostGen
    spawns:
    # Posters
    - id: RandomPosterLegit
      orGroup: content
    - id: RandomPainting
      prob: 0.05
      orGroup: content

  - !type:BoundaryWallPostGen
    tile: FloorSteel
    wall: WallSolid
    cornerWall: WallReinforced

  - !type:JunctionPostGen
    width: 1

  - !type:JunctionPostGen

  - !type:AutoCablingPostGen

  - !type:CornerClutterPostGen
    contents:
    - id: PottedPlantRandom
      amount: 1

