- type: entity
  name: "Blueprint: Empty"
  parent: BaseItem
  id: ThanatoBaseBlueprintModule
  description: An empty blueprint module. Absolutely useless.
  abstract: true
  components:
  - type: Sprite
    sprite: /Textures/_Thanatophobia/Objects/Misc/blueprint.rsi
    state: icon
  - type: Item
    size: Small
  - type: ContainerContainer
  - type: StaticPrice
    price: 500
  - type: DigitalMemoryBlueprint
    sound: /Audio/Machines/high_tech_confirm.ogg
