- type: spaceBiome
  id: TPAsteroidsStandard
  priority: 0
  noiseRanges:
    TPDefaultNoise:
    - 0, 1.1
  chunkComponents:
  - type: DebrisFeaturePlacerController
    densityNoiseChannel: Density
  - type: HotfixBiome
    biomes:
    - Meat
    - Sand
    - Ice
    - Standard
  - type: NoiseRangeCarver
    ranges:
      - 0.45, 0.55
    noiseChannel: Carver

- type: spaceBiome
  id: TPTheVoid
  priority: -500
  noiseRanges: {}
  chunkComponents:
  - type: DebrisFeaturePlacerController
    densityNoiseChannel: Density
    randomCancelChance: 1 # To stop the screaming.
